# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- script: |
    sudo apt update
    sudo apt install -y python3 python3-pip
    pip3 install bandit
  displayName: 'Install Bandit'
- script: |
    bandit -r setup.py
  workingDirectory: '$(Build.Repository.LocalPath)'
  displayName: 'Security check on harmless code'
#- script: |
#    bandit -r movie.py
#  workingDirectory: '$(Build.Repository.LocalPath)'
#  displayName: 'Security check on harmful code'

- script: |
    for file in ./*.py ;do bandit -r $file ;done
  workingDirectory: '$(Build.Repository.LocalPath)'
  displayName: 'All python files in directory'